language: ruby
rvm:
- 2.3.3
services:
- postgresql
env:
  global:
  - secure: nuHM+ImUpYTgppN2aIcHmx1K06vWZaEpnJesWzoS3kBBnuwm5c00VctuKhTJ/pXJns8KHMIBHm33jlye6qZbFGTlAalamKBZoDiXjPPGjKygYiPFoHrbneUpxpqmScHcxM8WW1QcQqDMruh2s/Yc+iEXh0CXQoHDVK7s+cq7sh+fS6SBOV6Ls6RAypf2XSBrUrcY1iqy+42Zyi58CymtxouZyH4awT5R2/isS10mEprVNmTJ8aVaedAFidJgdiJkn/CLezIfjzYpFSuiNepp6ceqzyo1FbSFHnHKRLkZOzk/ms6mQ1Yf9SHik+oU4MZACL+mxeG7vOAdbd2kNdK4zxe9Z8YW1kzGuBksx1xkbkjk6uxEC4TIJaaailMDHpI5nP8uxNv6kJw2sTmSbSNm8iQMq0O+VXEgM767+uKwZQo59AYq3NyL3p42hzOOaJpTj4M4CvHORHzTzEVKI1GHas53ylL3A56YA7mzRPziQ/MEA7DMV82IAFfaUnRChsekqpxw0TueEVD2IsSyv5Rx/093N+yGpiKA/v3Gi/FRTIH0LkPq7qd2NQFSbKsrFDyVDRRik3/NDGUmv3uE5JTyRV8HQ6R7gdOqSXPOpjJVAWRzPkQThTId+wlM6Nos/wbZ945c1l8bg8MQXqqauky1D+atMLYdFcd83y5WMi1nCi4=
bundler_args: "--without development --deployment"
cache: bundler
before_script:
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:create
- bundle exec rake db:migrate
script:
- bundle exec rake test
after_success:
- curl -X POST -H 'Authorization:Bearer '$LINE_API_KEY -F "message=Success" 'https://notify-api.line.me/api/notify'
after_failure:
- curl -X POST -H 'Authorization:Bearer '$LINE_API_KEY -F "message=Failure" 'https://notify-api.line.me/api/notify'
deploy:
  provider: heroku
  api_key:
    secure: R6ggeXuc3AQLSNslOQ9WZGiVl9KpaPbXT8aZnF/jDqupZbVfS8NgG4wIsw6/Mg9I2yCyPwRHasGL5PlgtVvgd/SUuxkBCDvxj15lGCL3B87Z8unAccFkquYOrW5y0FXN+xm4bePBZYZ3G49iEfFdP6nkmNKO7jhGpjYrO6vGFIlB4TwGDo4qT4a6YmovjJpbmLXRWcBZ3sy1KW+dDBqsId8c+6zQN845a+AN7303gK2JlfyA3hbRNqC92XRwr/T4/Yj8fNUZglIYvooKwYDZI/Xxe2jWq8RC4OJ/J3CeIo6cH1YV+tFOCKCz2tUu2z0woIY46wFb+8+v1XuJvYYcfpUYHxFTBSWX17Y4QYmph2Lx6coZnOhoPNFEuzSFMKSofiKT8JWb7Ow0tqId2BJysrxBgYm1r+VjNo4H4zMqSJeAsMB1UEG5HLDmKjLCXV+vV4XXz8U/yeZ7mb8UV6DvrI66EpiHqR81Qhz1GLwHIr+voRNX9slczRfN8p9aEYAqCpUjC3eZbL0G5WvbeWHhCmSn3HrzqV3nMn2N/ipiBfC4xLFpFyY1b30gnEGc9oRYCJyGUwXLPXBsiS9hevwh6f1wmhjk/FpvsAQi9XfJJdWAuwdnN+Dwa0vpaHZDDdoRJO5i0PkvcAgogdNLIzfzw9xADtyOZuXadNwiEaBvvRE=
  run:"rake db:migrate"
  app: sample000001
  on:
    repo: ryoutsugi/sample1
